apiVersion: v1
kind: ConfigMap
metadata:
  name: service-a
  namespace: helm-deployment
data:
  path-a.html: |
    "/path-a.html" on service-a
  path-b.html: |
    "/path-b.html" on service-a
  index.html: |
    "/" on service-a  
  404.html: |
    service-a 404 page
